### ISSUE TITLE
采纳 Pull Request 问题

### ISSUE THREAD

**Issue by easyhjq** [ituring/first-pr#1029]
when i git push it will hints are as follows ：

![1512527790 1](https://user-images.githubusercontent.com/34156313/33641674-7d4b79d8-da71-11e7-93f3-97366cd1fb46.jpg)

**Comment by stardance** [comment]
you should push it into your's **forked** repository,and then,execute pull request to "**first-pr**" repository

**Comment by easyhjq** [comment]
I have executed pull request to "**first-pr**"  repository。
Now i am  in accordance with the instructions on the book to do that。
The author said that if i had executed pull request before，then i would have the permissions with management of this repository。
I want to handle the pull request of myself 。

**Comment by easyhjq** [comment]
I have executed pull request to "first-pr" repository。
Now i am in accordance with the instructions on the book to do that。
The author said that if i had executed pull request before，then i would have the permissions with management of this repository。
I want to handle the pull request of myself 。 @stardance

**Comment by easyhjq** [comment]
I saw that some closed issues，there are some similar questions as my 。
Thank you all the same @stardance
