### ISSUE TITLE
书上说只要发送了pull request就会获得原仓库的管理权限，但是我发送后还是没有权限，不能merge,求大神解答

### ISSUE THREAD

**Issue by ghost** [ituring/first-pr#1059]
书上说只要发送了pull request就会获得原仓库的管理权限，但是我发送后还是没有权限，不能merge,求大神解答

**Comment by amaruk** [comment]
默认并不会自动添加权限，请尝试@一下liubin，申请协作维护原仓库的merge权限。
原仓库一般来说只Merge读者留言的pull request，不接受其他部分的修改，比较简单，如果想尝试复杂的pull request，可以自行注册两个GitHub账户尝试发送和接受pull request。

**Comment by chengtaowan** [comment]
楼上 +1

**Comment by shirley-wbw** [comment]
既然读者留言的PR一般都会接受，那不是闲的没事就可以来留言啦，这相当于留言板了吶🐰。 @sysuxuhr 不能解决，像2楼说的那样，2楼应该是有这个权限，我看到他接受了一些PR。

**Comment by sysuxuhr** [comment]
请问解决了没有？我也是只修改留言部分，push后没有权限修改。

**Comment by 0x10C** [comment]
同 push了显示permission denied

**Comment by wusaifei** [comment]
@dwj-scut @amaruk @chengtaowan @shirley-wbw @sysuxuhr  我的也出现了这个问题，push不成功，没有权限之类的，我感觉应该是把仓库放在C盘的原因，在获取权限的时候我们无法读取C盘里面的仓库。  解决办法，我直接将仓库用Github Desktop打开，然后直接修改index文件，然后在Github Desktop上pull request就解决了。先在上面添加新的分支，然后再仓库中修改文件，最后commit to work 就行了

**Comment by wusaifei** [comment]
![1](https://user-images.githubusercontent.com/27795216/45197431-c6337d80-b293-11e8-9a9d-6d50f2da24cc.PNG)
![2](https://user-images.githubusercontent.com/27795216/45197502-422dc580-b294-11e8-9b9a-367e2347c4b5.PNG)
![3](https://user-images.githubusercontent.com/27795216/45197537-68536580-b294-11e8-939f-2142fcb53cb2.PNG)

**Comment by amaruk** [comment]
@wusaifei
即使对ituring/first-pr发起pull request并被接受，也不会自动获取改仓库的管理权限。请参考我在1楼的回复。
对fork出来的自己的仓库随时可以push，和本地存储的分区无关。对无权限push的仓库，即使使用git图形界面也无法push，只能通过pull request请求merge变更。

**Comment by wusaifei** [comment]
@amaruk 谢谢你得解答可能是我理解错了，抱歉。因为刚开始的时候一直出现pull question请求无权限，所以才采用其他的方式。我想问一下用Git bash Here 进行push，为什么一直显示无权限呢？

**Comment by amaruk** [comment]
一般往自己仓库的远程分支push是不会有权限问题的，除非git bash here里配置的用户与在github上创建仓库的用户不同。
push到别人的远程仓库如果有权限问题，很可能是没有该仓库的管理权限，需要向仓库有权限的用户请求添加管理权限。
如果不是很理解的话可以申请两个github账户，尝试push到不同账户的仓库。

**Comment by wusaifei** [comment]
@amaruk 好的 谢谢 我试一试

**Comment by youcou12** [comment]
@liubin 
 请帮我增加merge权限，我提交的时候也没有权限。

**Comment by vangook** [comment]
建议好好看下书，理清一下逻辑。要想pull request,你直接往原来仓库push肯定是没有权限的，这也不是一个完整PR应有的流程和逻辑。

应该是：**Fork一份到为自己的repo** --> **git clone到本地** --> **本地创建新branch，修改代码** --> **git push origin [新建的分支名]** --> **github上切换至[新建的分支名]这个分支** --> **pull request** --> **系统检查Merge冲突并等待原仓库审核**

建议各位仔细体会一下，也是新手，欢迎交流:)

**Comment by vangook** [comment]
@liubin 大佬，我想申请一下维护仓库可以嘛 🥇

**Comment by liubin** [comment]
fork & PR 不需要权限，如果想在这个Repo里merge，则需要申请。

@vangook 请查看邀请。

**Comment by Seraph1990** [comment]
@liubin
大佬，请帮我增加merge权限，谢谢！

**Comment by Zhang3zhe** [comment]
@liubin 大佬，也请帮我增加merge权限，多谢！

**Comment by liubin** [comment]
@Seraph1990 @Zhang3zhe 请接收一下邀请。

**Comment by Zhang3zhe** [comment]
已收到，谢谢

**Comment by LightmanLu** [comment]
Add  my impression @liubin

**Comment by dwj-scut** [comment]
testtesttesttesttesttest




At 2019-04-18 09:52:33, "LightmanLu" <notifications@github.com> wrote:


Add my impression @liubin

**Comment by nonusx** [comment]
@liubin 给我个merge权限可以嘛？

**Comment by liubin** [comment]
@368573607 done
