### ISSUE TITLE
为什么这个仓库保管着Github Pages的源代码

### ISSUE THREAD

**Issue by snowman** [ituring/first-pr#1082]
正常来说不是应该创建一个ituring/ituring.github.io的仓库才行吗...

**Comment by SharryXu** [comment]
你这个路径对于组织就是有个总网站或者对于个人而言是个博客（直接用master分支）。如果是每个仓库下的gh_pages分支的话，就是这个仓库的网站。对于这里的first-pr，我觉得是第二种更合适。:smile:

**Comment by snowman** [comment]
![abc](https://user-images.githubusercontent.com/16096559/41816043-f9b4e232-77ad-11e8-9481-ca0e6f26facb.png)
