### ISSUE TITLE
6.3 pull request 时出现了如下问题

### ISSUE THREAD

**Issue by wusaifei** [ituring/first-pr#1287]
$ git push origin work
remote: Permission to ituring/first-pr.git denied to wusaifei.
fatal: unable to access 'https://github.com/ituring/first-pr.git/': The requested URL returned error: 403
怎么解决？

**Comment by WilliamsCeng** [comment]
在git中push 的接收方，应该是我们自己fork过来的、在我们自己GitHub账号下的仓库
