### ISSUE TITLE
为啥我在第7章接受Pull Request最后一步卡住了，提示我没有权限？

### ISSUE THREAD

**Issue by Finax** [ituring/first-pr#136]
$ git push
Enter passphrase for key '/c/Users/cc/.ssh/id_rsa':
Enter passphrase for key '/c/Users/cc/.ssh/id_rsa':
ERROR: Permission to ituring/first-pr.git denied to Finax.
fatal: Could not read from remote repository.

上面是提示消息。

**Comment by liubin** [comment]
你这个 id_rsa 文件设置密码了？权限是否是600？

另外，你现在是哪个分支？不会是master吧？

**Comment by Finax** [comment]
下面是我合并后的目录结构
yolanda@Haier-PC MINGW32 ~/first-pr (gh-pages)
$ git branch -a
- gh-pages
  pr1
  work
  
  remotes/RookieFromChina/feature/move-jquery-from-cdn-to-local
  remotes/RookieFromChina/gh-pages
  remotes/RookieFromChina/work
  remotes/origin/HEAD -> origin/gh-pages
  remotes/origin/feature/move-jquery-from-cdn-to-local
  remotes/origin/gh-pages

我从RookieFromChina用户合并到gh-pages 分支，然后push。，合并结果在gh-pages分支上。 

然后我push gh-pages分支。
yolanda@Haier-PC MINGW32 ~/first-pr (gh-pages)
$ git push

系统提示我输入账号密码，我就输入了自己的Git hub 账号密码。
Enter passphrase for key '/c/Users/yolanda/.ssh/id_rsa':
Enter passphrase for key '/c/Users/yolanda/.ssh/id_rsa':

回车后，系统显示为：
ERROR: Permission to ituring/first-pr.git denied to Finax.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

以上是我的操作。我在您书里看到一句，写着只有该项目的contributor 才有权限push，所以我就在想是不是我权限不够，所以问下您。如果我权限是有的，那应该是我的设置问题，我再看一遍书了再试。

感谢您百忙中的解答，从书中也学到了许多东西，书的纸张质量很好，看到中间都有点折不动了，O(∩_∩)O

祝： 圣诞快乐

**Comment by liubin** [comment]
应该是权限问题。有些分支是可以设置不允许直接push的。

你可以push到自己的分支，然后通过PR来合并。
