### ISSUE TITLE
书看了几遍还是迷迷糊糊能帮帮我吗？

### ISSUE THREAD

**Issue by ghost** [ituring/first-pr#14]

**Comment by liubin** [comment]
有什么问题你可以在这里提出。

**Comment by yelinlin** [comment]
我觉得前面的8章还是很好懂的，就是后面的与Github相互协作的工具以及服务不好懂，尤其测试和部署什么的 :sob:

**Comment by datascitest** [comment]
> 就是后面的与Github相互协作的工具以及服务不好懂

找几个朋友一起开发一个项目，过程中使用这些工具和服务，很快就会熟悉了

**Comment by alwayrun** [comment]
加入现有的开源组织，参与其中去就熟悉了 :+1:

**Comment by piperck** [comment]
@yelinlin 对的 找几个朋友 把功能用起来 就明白了。。其他 的 等到 公司实际使用的实用多用也就明白啦。

**Comment by IhInspiration** [comment]
@liubin 你好，请问，那个hub怎么安装？我在Git Bash 输入hub --version会出现 can't load git version

**Comment by weiwei91** [comment]
推荐使用 sourcetree   可以和github  完美配合，不用记忆那么多命令

**Comment by ghost** [comment]
> 找几个朋友一起开发一个项目，过程中使用这些工具和服务，很快就会熟悉了

可以自己再注册一个或多个github账号，然后打开chrome的[多开模式](http://jingyan.baidu.com/article/2a138328b5ceea074a134fd2.html)，新开的账号的操作就在网页端操作。
可以模拟下多人合作和其他功能

**Comment by adintr** [comment]
在网站上浏览看到的全是英文的项目，怎样能找到中文的项目吗？

**Comment by zhanwen** [comment]
hub命令在win下安装不成功呀

**Comment by IhInspiration** [comment]
你是什么错误呀

**Comment by zhanwen** [comment]
书上面对win的操作，不能用

**Comment by IhInspiration** [comment]
我书没在身边，你大概说下书上怎么弄的，我给忘记了

**Comment by piperck** [comment]
用git 不用mac 不是找自残吗

**Comment by zhanwen** [comment]
# 吼吼

**Comment by xuepeilei** [comment]
哇塞

**Comment by WellKnight908** [comment]
你得把你的问题说出来呀

**Comment by x5forever** [comment]
好好学习，天天向上

**Comment by vfolee** [comment]
在windows下的编辑器我一直没搞好，不知道怎么保存和退出

**Comment by IhInspiration** [comment]
详细查看vim操作命令，保存并退出就用:wq，直接退出用:q!

**Comment by ghost** [comment]
test

**Comment by renjie223** [comment]
another test

**Comment by ghost** [comment]
git 还是要用Linux/mac的， Windows的CLI 以及\ …在Windows下很难真的学会

**Comment by MarvinWenS** [comment]
用Windows学习git很难学

**Comment by taijieChen** [comment]
建议学习一下linux的基础命令

**Comment by ghost** [comment]
@yelinlin  你可以申请2个Github账户啊来模拟pullRequest，pullRequest这个你不能从字面上来理解，很容易误导人。它的意思是请求 <b>对方(主仓库方)接受您的请求(改动的代码)</b>

**Comment by ghost** [comment]
@CarryWZ  怎么就很难学了？

**Comment by cnmartinxu** [comment]
**迷迷糊糊是因为不清楚Distributed Version Control Systems和Local Version Control Systems与Centralized Version Control Systems的区别吗？**，那么请看这里 https://git-scm.com/book/zh/v2/%E8%B5%B7%E6%AD%A5-%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E6%8E%A7%E5%88%B6
**或是不熟悉各种Distributed Workflows吗？**  建议看这里 https://git-scm.com/book/zh/v2/%E5%88%86%E5%B8%83%E5%BC%8F-Git-%E5%90%91%E4%B8%80%E4%B8%AA%E9%A1%B9%E7%9B%AE%E8%B4%A1%E7%8C%AE

**Comment by ghost** [comment]
@cnmartinxu  建议你去下载个git 然后根据入门教程操作呀。

**Comment by cnmartinxu** [comment]
@NeedFSpeed 哈哈，好呀，能跟你模拟一下工作流程吗？

**Comment by ghost** [comment]
@cnmartinxu  你可以新建2个账户呀...

**Comment by amaruk** [comment]
我建了一个仓库，自己用两个账户来回测试，地址如下：
https://github.com/amaruk/PullRequestTest
大家可以往这里pull request，我收到之后会给你写这个仓库的权限，这样以后再有新的pull request大家都可以试着去处理，也可以约好一起测试多人开发。

**Comment by Maidi1990** [comment]
@piperck git不是用linux最好吗？还有，**第九章介绍的工具真正根据自己情况用起来**才是真的看懂这本书。#14

**Comment by ghost** [comment]
都差不多吧，WSL 下用 Linux (include git) 更适合有续航考量的笔记本，作为 terminal 甚至主力。

**Comment by zhanwen** [comment]
更多的是在实战中用到，自己才能体会得到

**Comment by easyhjq** [comment]
**孰能生巧**

**Comment by yangyang14641** [comment]
推荐68-69页的内容 LearnGitBranching https://learngitbranching.js.org  非常形象的树形结构加上很有游戏趣味和启发性的学习git命令的方式。动手实战是关键。

**Comment by buzhy** [comment]
为什么我在git bash上敲命令相应非常慢啊，真的非常慢，一个ls 起码需要5秒钟，

**Comment by zhanwen** [comment]
@buzhy 是不是内存不够用了，或者是你目录下的文件过多导致的。

**Comment by Ascot1** [comment]
一边看一边动手操作，这个是最好的

**Comment by visioshine** [comment]
你好，我也是刚刚学习GitHub，用的64位 Windows系统，一边看书，一遍在Git Bash上实践，一天学了有书的一半了，还算顺畅。学而不思则罔，静下心来，多思考，多操作，你的状态会越来越好的！

**Comment by youcou12** [comment]
@liubin 
 刘老师，你好！ 我按照书中第7章操作进行pull request,提示没有权限，无法进行合并，请帮我开通merge权限，谢谢！

**Comment by tjwait** [comment]
需要实际应用在工作中，就会慢慢学会！

**Comment by wenjianQL** [comment]
只是看怕是很难熟练掌握，用的多就会了

**Comment by Jiwangreal** [comment]
我最喜欢的章节就是：模拟实战开发😂

**Comment by leevison** [comment]
来此一游呵呵

**Comment by douDear** [comment]
第一次在github留下自己的脚印,O(∩_∩)O

**Comment by douDear** [comment]
fix #24

**Comment by lleon2017** [comment]
no pain no gain

**Comment by pstudy** [comment]
第一次在github留下自己的脸印,O(∩_∩)O

**Comment by jalain** [comment]
@liubin 
刘老师，我在进行push的时候输入秘钥以后提示没有权限，请问如何才能获得权限？

**Comment by liubin** [comment]
> @liubin
> 刘老师，我在进行push的时候输入秘钥以后提示没有权限，请问如何才能获得权限？

你的操作步骤？
push只能push到自己的repo。不能push到这里。

**Comment by jalain** [comment]
> > @liubin
> > 刘老师，我在进行push的时候输入秘钥以后提示没有权限，请问如何才能获得权限？
> 
> 你的操作步骤？
> push只能push到自己的repo。不能push到这里。

哦哦，谢谢刘老师，我是按照书上第7章的步骤做的，就是首先fork了ituring/first-pr，然后clone到本地仓库，接着找到了包含commit的pull request，把他设置为本地仓库的远程仓库获取发送方的仓库数据(我没有选自己的，因为在网页上进行操作的时候，里面提示好像不可以直接接受自己的pull request)。然后对数据进行fetch，建立检查分支合并pull request并删除分支，然后切换到主分支，进行合并，最后通过Git diff进行检查，在检查以后进行push。但是进行push操作时，在输入完秘钥以后就显示没有权限了。具体的信息是：Error: permission to ituring/first-pr.git denied to 我的用户名，fatal: could not read from remote repository. please make sure you have correct access rights and the repository exists. 我在自己的账户里面可以看到ituring/first-pr这个repository，那要怎样才能获得权限呢？我的哪一步操作有问题呢？
谢谢，刘老师

**Comment by liubin** [comment]
@jalain 你只能往自己的账号下的repo push代码，然后创建 pr

**Comment by jalain** [comment]
> @jalain 你只能往自己的账号下的repo push代码，然后创建 pr

刘老师，我已经按照书中的第6章进行过相应的操作了，也创建了pr的请求。因为在书里第7章接收pull request部分的第142页看到说只要在第6章中发送过PR，就会得到该仓库的权限，所以想按照第7章的内容以仓库维护者的身份处理下新发送的PR。然后就遇到了这一情况。可能是我什么地方理解错了，还以为可以直接处理PR到原来的Repo。

**Comment by liubin** [comment]
@jalain 

1. 看一下你的remote都是什么：

```
git remote -v
```

2. 看当前分支对应的GitHub分支

```
git status

```

把这两个命令的结果发一下。

**Comment by jalain** [comment]
> @jalain
> 
> 1. 看一下你的remote都是什么：
> 
> ```
> git remote -v
> ```
> 
> 1. 看当前分支对应的GitHub分支
> 
> ```
> git status
> ```
> 
> 把这两个命令的结果发一下。

刘老师，这个是我进行git remote -v的结果
jalain git@github.com:jalain/first-pr(fetch)
jalain git@github.com:jalain/first-pr(push)
origin git@github.com:ituring/first-pr.git(fetch)
origin git@github.com:ituring/first-pr.git(push)
xuyuzhuang11 git@github.com:xuyuzhuang11/first-pr.git(fetch)
xuyuzhuang11 git@github.com:xuyuzhuang11/first-pr.git(push)

这个是我进行git status以后的结果
on branch gh-pages
your branch is ahead of 'origin/gh-pages' by 3 commits.
(use "git push" to publish your local commits)

nothing to commit, working tree clean.

**Comment by jalain** [comment]
> @jalain
> 
> 1. 看一下你的remote都是什么：
> 
> ```
> git remote -v
> ```
> 
> 1. 看当前分支对应的GitHub分支
> 
> ```
> git status
> ```
> 
> 把这两个命令的结果发一下。

刘老师，这个是我进行git remote -v的结果
jalain git@github.com:jalain/first-pr(fetch)
jalain git@github.com:jalain/first-pr(push)
origin git@github.com:ituring/first-pr.git(fetch)
origin git@github.com:ituring/first-pr.git(push)
xuyuzhuang11 git@github.com:xuyuzhuang11/first-pr.git(fetch)
xuyuzhuang11 git@github.com:xuyuzhuang11/first-pr.git(push)

这个是我进行git status以后的结果
on branch gh-pages
your branch is ahead of 'origin/gh-pages' by 3 commits.
(use "git push" to publish your local commits)

nothing to commit, working tree clean.

**Comment by liubin** [comment]
```
your branch is ahead of 'origin/gh-pages' by 3 commits.
```
说明 你的 local  branch 指向的是 origin ，也就是 ituring 的repo
你应该用你自己 的 jalain ：

```
git push --set-upstream jalain gh-pages
```
然后在 GitHub 上通过 pr 合并到 ituring 仓库。

**Comment by jalain** [comment]
> ```
> your branch is ahead of 'origin/gh-pages' by 3 commits.
> ```
> 
> 说明 你的 local branch 指向的是 origin ，也就是 ituring 的repo
> 你应该用你自己 的 jalain ：
> 
> ```
> git push --set-upstream jalain gh-pages
> ```
> 
> 然后在 GitHub 上通过 pr 合并到 ituring 仓库。

刘老师，我按照你提供的方法已经成功的把修改提交到了远程仓库，但是目前我所做的所有操作都是在我的ituring/first-pr中进行的。但是目前我的仓库里面有两个与first-pr相关的仓库，一个是我fork过来的，另外一个不知道是什么，显示的是ituring/first-pr，那么这两个仓库的区别是什么呢？我直接在这个ituring/first-pr里面进行pr就可以了是吗？
![repo](https://user-images.githubusercontent.com/23609058/124216048-e6f5ad80-db27-11eb-8fa6-3e7c9ad72dcf.png)

**Comment by liubin** [comment]
ituring 是一个 org，就是图灵的组织的账号。
jalain是你个人的账号。

创建 pr 是在 ituring 的 first-pr项目下，选择从jalain下的first-pr合并到ituring下的first-pr仓库。

**Comment by liubin** [comment]
@jalain 你只有一个仓库，是从 ituring 下 fork 的。
![image](https://user-images.githubusercontent.com/1212008/124283724-cf95df00-db7e-11eb-8707-d1c59e520d07.png)

**Comment by jalain** [comment]
> ituring 是一个 org，就是图灵的组织的账号。
> jalain是你个人的账号。
> 
> 创建 pr 是在 ituring 的 first-pr项目下，选择从jalain下的first-pr合并到ituring下的first-pr仓库。

哦哦，谢谢刘老师，我大概明白了。
不过我还是有一个问题，我这个图里面为啥显示了这个ituring/first-pr呀。刚接触github不太熟悉这个布局，这个是我点了左上角的那个图像以后显示出来的。另外，刘老师，我可不可以这样理解，我从远程的ituring/first-pr重新获得了更新的数据，然后里面有一部分新的pull request.然后通过将这些pull request合并到我自己的jalain/first-pr，是不是也相当于进行了一次接受pull request的操作呢？
![repo](https://user-images.githubusercontent.com/23609058/124374734-6f16b700-dcd0-11eb-959e-ab8969d772ac.png)

**Comment by liubin** [comment]
@jalain 左上角那个不是属于你的repo，https://github.com/jalain?tab=repositories 才是。
在原仓库和fork的仓库之间同步，可以参考这里 https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by liubin** [comment]
这个 issue 先关掉了，讨论内容比较多样。
如果有问题，可以再看单独的新 issue 。
