### ISSUE TITLE
GitHub在国内访问很卡怎么办？

### ISSUE THREAD

**Issue by GamebabyRockSun** [ituring/first-pr#1659]
我Git Clone 命令 有些项目可以等一年都clone不完，网速只有几k，有什么好方法解决吗？

**Comment by amaruk** [comment]
是使用校园网的吗？可以尝试移动运营商的4G或者5G网络。

**Comment by GamebabyRockSun** [comment]
家庭宽带啊，伍佰兆起的哦，4K电影两倍速都不会卡的哦
