### ISSUE TITLE
关于仓库权限问题

### ISSUE THREAD

**Issue by Lechrond** [ituring/first-pr#1687]
在书中P142页专栏中提到只需提交过Pull Request就会获得仓库管理权限，但是我现在并不能Merge pill request？

**Comment by XiaoGe2030** [comment]
> 在书中P142页专栏中提到只需提交过Pull Request就会获得仓库管理权限，但是我现在并不能Merge pill request？
💯 我这边好像也是不行

**Comment by XiaoGe2030** [comment]
> 在书中P142页专栏中提到只需提交过Pull Request就会获得仓库管理权限，但是我现在并不能Merge pill request？

💯 我这边好像也是不行

**Comment by amaruk** [comment]
请@liubin申请管理权限。

**Comment by XiaoGe2030** [comment]
> 请@liubin申请管理权限。

@liubin 提交Pull Request后，并没有获得管理员权限，能否授予管理员权限？
😄

**Comment by liubin** [comment]
@Lechrond @XiaoGe2030 要想合并别人的PR，需要申请权限。如果需要的话回复一下本comment

**Comment by JerikChao** [comment]
comment

**Comment by JerikChao** [comment]
我没有权限，请合并我的PR，谢谢！ @liubin

**Comment by wewin-tech** [comment]
> @Lechrond @ XiaoGe2030要想合并别人的PR，需要申请权限。如果需要的话回复一下本comment

你好，我需要权限。3Q @liubin

**Comment by alicxo** [comment]
@liubin 请求申请管理员权限，多谢。

**Comment by liubin** [comment]
@alicxo @wewin-tech @JerikChao 已经邀请

**Comment by alicxo** [comment]
@liubin 感谢邀请我加入 ituring organization。但是我还是没有first-pr的merge request的权限。

**Comment by hzhaoy** [comment]
> @Lechrond @XiaoGe2030 要想合并别人的PR，需要申请权限。如果需要的话回复一下本comment

@liubin 你好，我要申请权限，谢谢！

**Comment by memcpy0** [comment]
@liubin 这边申请管理员权限，多谢了！

**Comment by sunzikun** [comment]
@liubin 申请管理员权限，谢谢！ :sun_with_face:

**Comment by superdjq** [comment]
@liubin 申请管理员权限，谢谢！

**Comment by nonusx** [comment]
> @Lechrond @XiaoGe2030 要想合并别人的PR，需要申请权限。如果需要的话回复一下本comment

申请一下权限

？怎么closed了呢？
