### ISSUE TITLE
P129-给原仓库设置 upstream 的名称

### ISSUE THREAD

**Issue by lucienyong** [ituring/first-pr#1786]
```
$ git remote add upstream git://github.com/octocat/Spoon-Knife.git
```
应该是下面的写法才对吧？
```
$ git remote add upstream git@github.com：octocat/Spoon-Knife.git
```

**Comment by ZachZheng0316** [comment]
> ```
> $ git remote add upstream git://github.com/octocat/Spoon-Knife.git
> ```
> 
> 应该是下面的写法才对吧？
> 
> ```
> $ git remote add upstream git@github.com：octocat/Spoon-Knife.git
> ```

两种写法都是可以的

**Comment by Z-nkk** [comment]
> ```
> $ git remote add upstream git://github.com/octocat/Spoon-Knife.git
> ```
> 
> 
> 应该是下面的写法才对吧？
> 
> 
> ```
> $ git remote add upstream git@github.com：octocat/Spoon-Knife.git
> ```
这两句写法都可以，一个是上面是使用的https连接

**Comment by liubin** [comment]
https 需要user/passwd认证，git的可以通过ssh key认证。
