### ISSUE TITLE
关于管理权限

### ISSUE THREAD

**Issue by floudk** [ituring/first-pr#1999]
按照书中操作后，在采纳Pull Request过程中得到
***ERROR: Permission to ituring/first-pr.git denied to XXX***
***Please make sure you have the correct access rights and the repository exists.***
打开Github后也并没有找到merge的选项，似乎我并没有管理权限，我也不太清楚管理权限的界面有什么区别，请问这个是什么请况？

**Comment by 368573607** [comment]
> 似乎我并没有管理权限

当然啦，设想一下，如果人人都有权利合并别人的pull request，那岂不是就乱套了？所以能够审查并合并别人pull request的人只有仓库的创建者和其邀请的项目工作人员。

我不知道我对你的问题描述理解对没有，你可以追加issue和我交流

**Comment by wzyys1** [comment]
我也遇到了同样的问题 🐶

**Comment by frankjm66** [comment]
同样的问题

**Comment by frankjm66** [comment]
P169: 关于本章和第 6 章提到的那个仓库，只要您在第 6 章中发送
过 Pull…Request，就会得到该仓库的管理权限..

我昨天发送过Pull Request, 需要等多久才可以获得管理权限?

**Comment by jalain** [comment]
我也遇到同样的问题

**Comment by Algo-Goer** [comment]
我也遇到了同样问题。  书中7.4小结还写着：只要您在第6章中发送过Pull Request，就会得到该仓库的管理权限，以便您对该仓库进行维护。各位可以参考本章内容，试着以仓库维护者的身份处理新送来的Pull Request。这样一来，各位读者就可以通过一个仓库，互相学习Pull Request收发双方的相关知识。
