### ISSUE TITLE
添加了PR，在第七章采纳PR时，push失败，请给我管理权限谢谢

### ISSUE THREAD

**Issue by Algo-Goer** [ituring/first-pr#2157]
git push
ERROR: Permission to ituring/first-pr.git denied to Algo-Goer.
fatal: Could not read from remote repository.

**Comment by Algo-Goer** [comment]
@liubin

**Comment by XxxuLimei** [comment]
您好，我也遇到了和您一样的问题，请问是给权限之后才可以push成功是吗？

**Comment by liubin** [comment]
> 您好，我也遇到了和您一样的问题，请问是给权限之后才可以push成功是吗？

push到自己的仓库是不需要申请额外权限，创建pr也不需要权限，只有合并这个仓库中的pr，才需要别的权限。
