### ISSUE TITLE
学习PR突然想到了一个问题，求解答

### ISSUE THREAD

**Issue by Wing-Sing** [ituring/first-pr#2190]
比如我们很多个人申请了PR，然后大家都是在同一行的地方进行修改，这样不会造成冲突吗？

**Comment by Wing-Sing** [comment]
比如我们这个项目，如果刚好有多个人在同一行写了impression，然后请求PR，第一个人申请的PR当然能通过，但是第二个呢？是不是就造成了冲突导致PR不成功？

**Comment by XxxuLimei** [comment]
这个问题在前面几节好像有说过
如果出现冲突之后，可以修改，比如现在可以按照时间顺序把评论加到某一个版本里，再进行close
不解决冲突的画无法完成合并，可以参考书上P57 :-)

**Comment by Wing-Sing** [comment]
> 

😄 谢谢
