### ISSUE TITLE
[WIP] 添加翻页功能

### ISSUE THREAD

**Issue by ChinaSK** [ituring/first-pr#256]
## 添加翻页功能 👍
- [x] 添加
- [ ] 编辑
- [ ] 删除

随着留言【感想】不断增多，为了缓解加载速度有必要添加翻页功能，进行向大家征求意见中。

**Comment by renjie223** [comment]
没用过写着网页的语言……有兴趣的可以试试

**Comment by shawnwang-sg** [comment]
I'm Coming~LOL

**Comment by vfr456** [comment]
翻页的话要用到动态网页吧 ， 这个不是静态的吗

**Comment by lojzes** [comment]
Are you ok?

**Comment by jeffjiang07** [comment]
不错啊

**Comment by zhangsw1412** [comment]
离开了数据库还真就不知道应该怎么翻页呢，期待有人实现

**Comment by amaruk** [comment]
已实现翻页功能。
详情查看Pull Request #930。
感谢@KokoTa的努力。
