### ISSUE TITLE
如何获得merge pull request权限？

### ISSUE THREAD

**Issue by amaruk** [ituring/first-pr#566]
并没有像书上所说，在发送过pull request之后就能获得merge pull request的权限。
目前打开pull request依然显示“Only those with write access to this repository can merge pull requests.”。

**Comment by koreyoshi1992** [comment]
是不是需要作者来merge呀，第七章学到最后没有权限

**Comment by amaruk** [comment]
让我们试试 @liubin 一下，同时引用一下@koreyoshi1992的Pull Request #571 。

**Comment by liubin** [comment]
需要赋予权限才行。 @amaruk

**Comment by amaruk** [comment]
我自己建立了仓库，用两个帐户测试了pull request和添加Collaborators获取权限的功能。
3Q。
