### ISSUE TITLE
P123页， git push origin work 出错

### ISSUE THREAD

**Issue by meshiguge** [ituring/first-pr#588]
123页， git push origin work 

ERROR: Permission to ituring/first-pr.git denied to meshiguge.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

－－ 
这是什么问题呢

**Comment by amaruk** [comment]
从错误信息分析，你应该是直接clone了ituring的仓库到本地，修改文件之后使用git push。但因为你并没有写ituring仓库的权限，所以无法push。
你再仔细看一下这章前面关于fork的内容。
应该先fork ituring的仓库到你自己的仓库，然后clone你自己的仓库到本地，修改，push到自己的仓库，最后从自己的仓库向ituring发起pull request。

**Comment by meshiguge** [comment]
谢谢
