### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by yichengsu** [ituring/first-pr#627]
请问从github上删除了一个分支，但是本地用 git branch -a 还是显示这个远程分支，怎么处理？

**Comment by yichengsu** [comment]
![image](https://cloud.githubusercontent.com/assets/13522803/23243822/556cbdf0-f9bc-11e6-9138-0aec7b39c5aa.png)

**Comment by amaruk** [comment]
git remote prune origin

**Comment by yichengsu** [comment]
感谢 @amaruk
