### ISSUE TITLE
已经发送了pull request，但是没有获取到管理权限啊

### ISSUE THREAD

**Issue by GainSury** [ituring/first-pr#631]

**Comment by amaruk** [comment]
参考 #566 
我自己建立了一个仓库，只要发送pull request，我会无条件添加管理权限：
https://github.com/amaruk/PullRequestTest.git
也可以自己申请一个小号，两个账号编辑一个仓库，来回pull request。

**Comment by liubin** [comment]
发 PR 和获得管理员权限是不同的两件事。

@amaruk  @GainSury 如果你们有兴趣长期维护这个仓库，可以给你们增加权限，能处理 PR 的 merge 操作。

**Comment by amaruk** [comment]
因为6.3章节末尾有译注说"示例仓库由译者和志愿者维护(包括尝试Pull Request的各位读者）"，刚开始学习的时候可能有点误解。
虽然才入门不久，如果可以的话，也想帮忙维护这个仓库，为大家做点贡献。

**Comment by liubin** [comment]
@amaruk 已添加，你可以试一下能不能 merge pr，有问题联系我。

**Comment by amaruk** [comment]
谢谢，等晚点收到pull request我试试。
